-- ============================================================================
-- SmartGuard Error Logs Table
-- ============================================================================
-- Objetivo: Persistir errores del servidor con contexto de usuario/empresa
-- Access: solo service_role (RLS restringe acceso a usuarios)
-- ============================================================================

create table if not exists public.error_logs (
  id         bigint generated by default as identity primary key,
  context    text not null,
  message    text not null,
  user_id    uuid references auth.users(id) on delete set null,
  company_id uuid references public.companies(id) on delete set null,
  extra      jsonb not null default '{}',
  created_at timestamptz not null default now()
);

-- Only service_role can read/write error_logs
alter table public.error_logs enable row level security;

create policy "Service role manages error_logs"
  on public.error_logs for all
  to service_role
  using (true)
  with check (true);

-- Index for querying by time and company
create index if not exists idx_error_logs_created_at
  on error_logs(created_at desc);

create index if not exists idx_error_logs_company_id
  on error_logs(company_id);
